/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Car;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author felipe
 */
public class CarRegister extends javax.swing.JFrame {

    /**
     * Creates new form CarRegister
     */
    Car car = new Car();

    public CarRegister() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroupTest = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        buttonGroup10 = new javax.swing.ButtonGroup();
        buttonGroup11 = new javax.swing.ButtonGroup();
        buttonGroup12 = new javax.swing.ButtonGroup();
        buttonGroup13 = new javax.swing.ButtonGroup();
        buttonGroup14 = new javax.swing.ButtonGroup();
        jLabelMake = new javax.swing.JLabel();
        jLabelModel = new javax.swing.JLabel();
        jLabelOptional = new javax.swing.JLabel();
        jPanelOptional = new javax.swing.JPanel();
        jCheckBoxAirConditioner = new javax.swing.JCheckBox();
        jCheckBoxHidraulicSteering = new javax.swing.JCheckBox();
        jCheckBoxEletricSteering = new javax.swing.JCheckBox();
        jCheckBoxEletricWindows = new javax.swing.JCheckBox();
        jCheckBoxAbs = new javax.swing.JCheckBox();
        jCheckBoxAirBag = new javax.swing.JCheckBox();
        jCheckBoxParkingAssistent = new javax.swing.JCheckBox();
        jCheckBoxAlarm = new javax.swing.JCheckBox();
        jCheckBoxEletricLocks = new javax.swing.JCheckBox();
        jCheckBoxRearWiper = new javax.swing.JCheckBox();
        jCheckBoxRearDefroster = new javax.swing.JCheckBox();
        jCheckBoxMp3Player = new javax.swing.JCheckBox();
        jCheckBoxBluetooth = new javax.swing.JCheckBox();
        jCheckBoxAlloyWheels = new javax.swing.JCheckBox();
        jLabelYear = new javax.swing.JLabel();
        jComboBoxYear = new javax.swing.JComboBox<>();
        jLabelColor = new javax.swing.JLabel();
        jTextFieldColor = new javax.swing.JTextField();
        jToggleButtonIpva = new javax.swing.JToggleButton();
        jLabelIpva = new javax.swing.JLabel();
        jLabelTransmission = new javax.swing.JLabel();
        jButtonClean = new javax.swing.JButton();
        jButtonSave = new javax.swing.JButton();
        jLabelSpeed = new javax.swing.JLabel();
        jComboBoxSpeed = new javax.swing.JComboBox<>();
        jLabelMileage = new javax.swing.JLabel();
        jLabelFuel = new javax.swing.JLabel();
        jPanelTransmission = new javax.swing.JPanel();
        jRadioButtonAutomatic = new javax.swing.JRadioButton();
        jRadioButtonAutomated = new javax.swing.JRadioButton();
        jRadioButtonManual = new javax.swing.JRadioButton();
        jFormattedTextFieldMileage = new javax.swing.JFormattedTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTreeFuel = new javax.swing.JTree();
        jTextFieldModel = new javax.swing.JTextField();
        jLabelDescription = new javax.swing.JLabel();
        jTextFieldMake = new javax.swing.JTextField();
        jProgressBar1 = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDescription = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelMake.setText("Make:");

        jLabelModel.setText("Model:");

        jLabelOptional.setText("Optional:");

        jCheckBoxAirConditioner.setText("Air Conditioner");

        jCheckBoxHidraulicSteering.setText("Hidraulic Steering");

        jCheckBoxEletricSteering.setText("Eletric Steering");
        jCheckBoxEletricSteering.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxEletricSteeringActionPerformed(evt);
            }
        });

        jCheckBoxEletricWindows.setText("Eletric Windows");

        jCheckBoxAbs.setText("ABS");

        jCheckBoxAirBag.setText("AirBag");

        jCheckBoxParkingAssistent.setText("Parking Assistent");

        jCheckBoxAlarm.setText("Alarm");

        jCheckBoxEletricLocks.setText("Electric Locks");

        jCheckBoxRearWiper.setText("Rear Wiper");

        jCheckBoxRearDefroster.setText("Rear Defroster");

        jCheckBoxMp3Player.setText("CD MP3 Player");

        jCheckBoxBluetooth.setText("Bluetooth");

        jCheckBoxAlloyWheels.setText("Alloy Wheels");

        javax.swing.GroupLayout jPanelOptionalLayout = new javax.swing.GroupLayout(jPanelOptional);
        jPanelOptional.setLayout(jPanelOptionalLayout);
        jPanelOptionalLayout.setHorizontalGroup(
            jPanelOptionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOptionalLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelOptionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelOptionalLayout.createSequentialGroup()
                        .addGroup(jPanelOptionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxParkingAssistent)
                            .addComponent(jCheckBoxAirBag)
                            .addComponent(jCheckBoxAbs)
                            .addComponent(jCheckBoxEletricWindows)
                            .addComponent(jCheckBoxEletricSteering)
                            .addComponent(jCheckBoxHidraulicSteering))
                        .addGap(56, 56, 56)
                        .addGroup(jPanelOptionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxRearWiper)
                            .addComponent(jCheckBoxEletricLocks)
                            .addComponent(jCheckBoxRearDefroster)
                            .addComponent(jCheckBoxMp3Player)
                            .addComponent(jCheckBoxBluetooth)
                            .addComponent(jCheckBoxAlloyWheels)))
                    .addGroup(jPanelOptionalLayout.createSequentialGroup()
                        .addComponent(jCheckBoxAirConditioner)
                        .addGap(76, 76, 76)
                        .addComponent(jCheckBoxAlarm)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelOptionalLayout.setVerticalGroup(
            jPanelOptionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOptionalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOptionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxAirConditioner)
                    .addComponent(jCheckBoxAlarm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelOptionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxHidraulicSteering)
                    .addComponent(jCheckBoxEletricLocks))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelOptionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxEletricSteering)
                    .addComponent(jCheckBoxRearWiper))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelOptionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxEletricWindows)
                    .addComponent(jCheckBoxRearDefroster))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelOptionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxAbs)
                    .addComponent(jCheckBoxMp3Player))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelOptionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxBluetooth, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCheckBoxAirBag))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelOptionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxParkingAssistent)
                    .addComponent(jCheckBoxAlloyWheels))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelYear.setText("Year:");

        jComboBoxYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980", "1979", "1978", "1977", "1976", "1975", "1974", "1973", "1972", "1971", "1970" }));

        jLabelColor.setText("Color:");

        jToggleButtonIpva.setLabel("Ok");

        jLabelIpva.setText("IPVA:");

        jLabelTransmission.setText("Transmission:");

        jButtonClean.setText("Clean");
        jButtonClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCleanActionPerformed(evt);
            }
        });

        jButtonSave.setText("Save");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jLabelSpeed.setText("Speed:");

        jComboBoxSpeed.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13+" }));

        jLabelMileage.setText("Mileage");

        jLabelFuel.setText("Fuel:");

        buttonGroup1.add(jRadioButtonAutomatic);
        jRadioButtonAutomatic.setText("Automatic");

        buttonGroup1.add(jRadioButtonAutomated);
        jRadioButtonAutomated.setText("Automated");

        buttonGroup1.add(jRadioButtonManual);
        jRadioButtonManual.setText("Manual");

        javax.swing.GroupLayout jPanelTransmissionLayout = new javax.swing.GroupLayout(jPanelTransmission);
        jPanelTransmission.setLayout(jPanelTransmissionLayout);
        jPanelTransmissionLayout.setHorizontalGroup(
            jPanelTransmissionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTransmissionLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(jPanelTransmissionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonManual)
                    .addComponent(jRadioButtonAutomated)
                    .addComponent(jRadioButtonAutomatic))
                .addContainerGap())
        );
        jPanelTransmissionLayout.setVerticalGroup(
            jPanelTransmissionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTransmissionLayout.createSequentialGroup()
                .addComponent(jRadioButtonManual)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRadioButtonAutomatic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonAutomated)
                .addGap(30, 30, 30))
        );

        jScrollPane2.setViewportView(jTreeFuel);

        jLabelDescription.setText("Description:");

        jTextAreaDescription.setColumns(20);
        jTextAreaDescription.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDescription);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelYear)
                                    .addComponent(jLabelMake))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jComboBoxYear, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(23, 23, 23)
                                        .addComponent(jLabelColor))
                                    .addComponent(jTextFieldMake))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addComponent(jLabelModel))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldColor, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldModel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabelIpva)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jToggleButtonIpva))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelTransmission)
                                        .addGap(18, 18, 18)
                                        .addComponent(jPanelTransmission, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(43, 43, 43)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabelSpeed)
                                                .addGap(33, 33, 33)
                                                .addComponent(jComboBoxSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabelMileage)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jFormattedTextFieldMileage, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelOptional)
                                        .addGap(18, 18, 18)
                                        .addComponent(jPanelOptional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelFuel)
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(35, 35, 35)
                                        .addComponent(jLabelDescription)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(jButtonSave)
                        .addGap(36, 36, 36)
                        .addComponent(jButtonClean))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(110, 110, 110))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMake)
                    .addComponent(jTextFieldMake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelModel)
                    .addComponent(jTextFieldModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelYear)
                    .addComponent(jComboBoxYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelColor)
                    .addComponent(jTextFieldColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelIpva)
                    .addComponent(jToggleButtonIpva))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelOptional)
                    .addComponent(jPanelOptional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelTransmission)
                        .addGap(105, 105, 105)
                        .addComponent(jLabelFuel))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelTransmission, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelSpeed)
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelMileage)
                                    .addComponent(jFormattedTextFieldMileage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jComboBoxSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelDescription)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSave)
                    .addComponent(jButtonClean))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed

        car.setMake(jTextFieldMake.getText());
        car.setModel(jTextFieldModel.getText());
        car.setYear(jComboBoxYear.getSelectedItem().toString());
        car.setColor(jTextFieldColor.getText());
        car.setDescription(jTextAreaDescription.getText());
        car.setIpva(jToggleButtonIpva.isSelected());
        car.setMileage(jFormattedTextFieldMileage.getText());
        car.setSpeed(jComboBoxSpeed.getSelectedItem().toString());

        if (jRadioButtonAutomated.isSelected()) {
            car.setTransmission(jRadioButtonAutomated.getText());
        } else if (jRadioButtonAutomatic.isSelected()) {
            car.setTransmission(jRadioButtonAutomatic.getText());
        } else if (jRadioButtonManual.isSelected()) {
            car.setTransmission(jRadioButtonManual.getText());
        }

        ArrayList<String> optionals = new ArrayList<>();

        if (jCheckBoxAbs.isSelected()) {
            optionals.add(jCheckBoxAbs.getText());
            car.setOptional(optionals);
        }
        if (jCheckBoxAirBag.isSelected()) {
            optionals.add(jCheckBoxAirBag.getText());
            car.setOptional(optionals);
        }
        if (jCheckBoxAirConditioner.isSelected()) {
            optionals.add(jCheckBoxAirConditioner.getText());
            car.setOptional(optionals);
        }
        if (jCheckBoxAlarm.isSelected()) {
            optionals.add(jCheckBoxAlarm.getText());
            car.setOptional(optionals);
        }
        if (jCheckBoxAlloyWheels.isSelected()) {
            optionals.add(jCheckBoxAlloyWheels.getText());
            car.setOptional(optionals);
        }
        if (jCheckBoxBluetooth.isSelected()) {
            optionals.add(jCheckBoxBluetooth.getText());
            car.setOptional(optionals);
        }
        if (jCheckBoxEletricLocks.isSelected()) {
            optionals.add(jCheckBoxEletricLocks.getText());
            car.setOptional(optionals);
        }
        if (jCheckBoxEletricSteering.isSelected()) {
            optionals.add(jCheckBoxEletricSteering.getText());
            car.setOptional(optionals);
        }
        if (jCheckBoxEletricWindows.isSelected()) {
            optionals.add(jCheckBoxEletricWindows.getText());
            car.setOptional(optionals);
        }
        if (jCheckBoxHidraulicSteering.isSelected()) {
            optionals.add(jCheckBoxHidraulicSteering.getText());
            car.setOptional(optionals);
        }
        if (jCheckBoxMp3Player.isSelected()) {
            optionals.add(jCheckBoxMp3Player.getText());
            car.setOptional(optionals);
        }
        if (jCheckBoxParkingAssistent.isSelected()) {
            optionals.add(jCheckBoxParkingAssistent.getText());
            car.setOptional(optionals);
        }
        if (jCheckBoxRearDefroster.isSelected()) {
            optionals.add(jCheckBoxRearDefroster.getText());
            car.setOptional(optionals);
        }
        if (jCheckBoxRearWiper.isSelected()) {
            optionals.add(jCheckBoxRearWiper.getText());
            car.setOptional(optionals);
        }

        car.setFuel("");

        JOptionPane.showMessageDialog(this, "Ok");

    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButtonCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCleanActionPerformed
        // TODO add your handling code here:

        jTextAreaDescription.setText("");
        jTextFieldColor.setText("");
        jTextFieldMake.setText("");
        jTextFieldModel.setText("");
        jComboBoxYear.setSelectedItem("2018");
        jComboBoxSpeed.setSelectedItem("1");
    }//GEN-LAST:event_jButtonCleanActionPerformed

    private void jCheckBoxEletricSteeringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxEletricSteeringActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxEletricSteeringActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup10;
    private javax.swing.ButtonGroup buttonGroup11;
    private javax.swing.ButtonGroup buttonGroup12;
    private javax.swing.ButtonGroup buttonGroup13;
    private javax.swing.ButtonGroup buttonGroup14;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.ButtonGroup buttonGroupTest;
    private javax.swing.JButton jButtonClean;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JCheckBox jCheckBoxAbs;
    private javax.swing.JCheckBox jCheckBoxAirBag;
    private javax.swing.JCheckBox jCheckBoxAirConditioner;
    private javax.swing.JCheckBox jCheckBoxAlarm;
    private javax.swing.JCheckBox jCheckBoxAlloyWheels;
    private javax.swing.JCheckBox jCheckBoxBluetooth;
    private javax.swing.JCheckBox jCheckBoxEletricLocks;
    private javax.swing.JCheckBox jCheckBoxEletricSteering;
    private javax.swing.JCheckBox jCheckBoxEletricWindows;
    private javax.swing.JCheckBox jCheckBoxHidraulicSteering;
    private javax.swing.JCheckBox jCheckBoxMp3Player;
    private javax.swing.JCheckBox jCheckBoxParkingAssistent;
    private javax.swing.JCheckBox jCheckBoxRearDefroster;
    private javax.swing.JCheckBox jCheckBoxRearWiper;
    private javax.swing.JComboBox<String> jComboBoxSpeed;
    private javax.swing.JComboBox<String> jComboBoxYear;
    private javax.swing.JFormattedTextField jFormattedTextFieldMileage;
    private javax.swing.JLabel jLabelColor;
    private javax.swing.JLabel jLabelDescription;
    private javax.swing.JLabel jLabelFuel;
    private javax.swing.JLabel jLabelIpva;
    private javax.swing.JLabel jLabelMake;
    private javax.swing.JLabel jLabelMileage;
    private javax.swing.JLabel jLabelModel;
    private javax.swing.JLabel jLabelOptional;
    private javax.swing.JLabel jLabelSpeed;
    private javax.swing.JLabel jLabelTransmission;
    private javax.swing.JLabel jLabelYear;
    private javax.swing.JPanel jPanelOptional;
    private javax.swing.JPanel jPanelTransmission;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JRadioButton jRadioButtonAutomated;
    private javax.swing.JRadioButton jRadioButtonAutomatic;
    private javax.swing.JRadioButton jRadioButtonManual;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaDescription;
    private javax.swing.JTextField jTextFieldColor;
    private javax.swing.JTextField jTextFieldMake;
    private javax.swing.JTextField jTextFieldModel;
    private javax.swing.JToggleButton jToggleButtonIpva;
    private javax.swing.JTree jTreeFuel;
    // End of variables declaration//GEN-END:variables
}
