/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import model.Calculo;

/**
 *
 * @author lab-suporte
 */
public class FormCalculadora extends javax.swing.JFrame {

    /**
     * Creates new form FormCalculadora
     */
    public FormCalculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jpanelBase = new javax.swing.JPanel();
        jpanelVisor = new javax.swing.JPanel();
        jtxtViewer = new javax.swing.JTextField();
        jpanelBotoes = new javax.swing.JPanel();
        jbtnClear = new javax.swing.JButton();
        jbtnComma = new javax.swing.JButton();
        jbtnDivide = new javax.swing.JButton();
        jbtnSeven = new javax.swing.JButton();
        jbtnEight = new javax.swing.JButton();
        jbtnNine = new javax.swing.JButton();
        jbtnMultiply = new javax.swing.JButton();
        jbtnFour = new javax.swing.JButton();
        jbtnFive = new javax.swing.JButton();
        jbtnSix = new javax.swing.JButton();
        jbtnSubtract = new javax.swing.JButton();
        jbtnOne = new javax.swing.JButton();
        jbtnTwo = new javax.swing.JButton();
        jbtnThree = new javax.swing.JButton();
        jbtnAdd = new javax.swing.JButton();
        jbtnZero = new javax.swing.JButton();
        jbtnEquals = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        setPreferredSize(new java.awt.Dimension(250, 300));
        setResizable(false);

        jpanelVisor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(76, 76, 76)));

        jtxtViewer.setEditable(false);
        jtxtViewer.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jtxtViewer.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtViewer.setText("0");

        javax.swing.GroupLayout jpanelVisorLayout = new javax.swing.GroupLayout(jpanelVisor);
        jpanelVisor.setLayout(jpanelVisorLayout);
        jpanelVisorLayout.setHorizontalGroup(
            jpanelVisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtxtViewer)
        );
        jpanelVisorLayout.setVerticalGroup(
            jpanelVisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtxtViewer)
        );

        jpanelBotoes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(93, 93, 93)));
        jpanelBotoes.setLayout(new java.awt.GridBagLayout());

        jbtnClear.setText("C");
        jbtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnClearActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 100.0;
        gridBagConstraints.weighty = 75.0;
        jpanelBotoes.add(jbtnClear, gridBagConstraints);

        jbtnComma.setText(",");
        jbtnComma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCommaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 50.0;
        gridBagConstraints.weighty = 75.0;
        jpanelBotoes.add(jbtnComma, gridBagConstraints);

        jbtnDivide.setText("/");
        jbtnDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDivideActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 50.0;
        gridBagConstraints.weighty = 75.0;
        jpanelBotoes.add(jbtnDivide, gridBagConstraints);

        jbtnSeven.setText("7");
        jbtnSeven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSevenActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 50.0;
        gridBagConstraints.weighty = 75.0;
        jpanelBotoes.add(jbtnSeven, gridBagConstraints);

        jbtnEight.setText("8");
        jbtnEight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEightActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 50.0;
        gridBagConstraints.weighty = 75.0;
        jpanelBotoes.add(jbtnEight, gridBagConstraints);

        jbtnNine.setText("9");
        jbtnNine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNineActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 50.0;
        gridBagConstraints.weighty = 75.0;
        jpanelBotoes.add(jbtnNine, gridBagConstraints);

        jbtnMultiply.setText("*");
        jbtnMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMultiplyActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 50.0;
        gridBagConstraints.weighty = 75.0;
        jpanelBotoes.add(jbtnMultiply, gridBagConstraints);

        jbtnFour.setText("4");
        jbtnFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnFourActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 50.0;
        gridBagConstraints.weighty = 75.0;
        jpanelBotoes.add(jbtnFour, gridBagConstraints);

        jbtnFive.setText("5");
        jbtnFive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnFiveActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 50.0;
        gridBagConstraints.weighty = 75.0;
        jpanelBotoes.add(jbtnFive, gridBagConstraints);

        jbtnSix.setText("6");
        jbtnSix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSixActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 50.0;
        gridBagConstraints.weighty = 75.0;
        jpanelBotoes.add(jbtnSix, gridBagConstraints);

        jbtnSubtract.setText("-");
        jbtnSubtract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSubtractActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 50.0;
        gridBagConstraints.weighty = 75.0;
        jpanelBotoes.add(jbtnSubtract, gridBagConstraints);

        jbtnOne.setText("1");
        jbtnOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnOneActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 50.0;
        gridBagConstraints.weighty = 75.0;
        jpanelBotoes.add(jbtnOne, gridBagConstraints);

        jbtnTwo.setText("2");
        jbtnTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTwoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 50.0;
        gridBagConstraints.weighty = 75.0;
        jpanelBotoes.add(jbtnTwo, gridBagConstraints);

        jbtnThree.setText("3");
        jbtnThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnThreeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 50.0;
        gridBagConstraints.weighty = 75.0;
        jpanelBotoes.add(jbtnThree, gridBagConstraints);

        jbtnAdd.setText("+");
        jbtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 50.0;
        gridBagConstraints.weighty = 75.0;
        jpanelBotoes.add(jbtnAdd, gridBagConstraints);

        jbtnZero.setText("0");
        jbtnZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnZeroActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 75.0;
        jpanelBotoes.add(jbtnZero, gridBagConstraints);

        jbtnEquals.setText("=");
        jbtnEquals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEqualsActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 100.0;
        gridBagConstraints.weighty = 75.0;
        jpanelBotoes.add(jbtnEquals, gridBagConstraints);

        javax.swing.GroupLayout jpanelBaseLayout = new javax.swing.GroupLayout(jpanelBase);
        jpanelBase.setLayout(jpanelBaseLayout);
        jpanelBaseLayout.setHorizontalGroup(
            jpanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanelVisor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpanelBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
        jpanelBaseLayout.setVerticalGroup(
            jpanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelBaseLayout.createSequentialGroup()
                .addComponent(jpanelVisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpanelBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanelBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanelBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnClearActionPerformed
        // TODO add your handling code here:
        this.jtxtViewer.setText("0");
    }//GEN-LAST:event_jbtnClearActionPerformed

    private void jbtnCommaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCommaActionPerformed
        // TODO add your handling code here:
        String aux = this.jtxtViewer.getText();
        if (!aux.contains(".")) {
            this.jtxtViewer.setText(aux + ".");
        }
    }//GEN-LAST:event_jbtnCommaActionPerformed

    private void jbtnZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnZeroActionPerformed
        // TODO add your handling code here:
        String aux = this.jtxtViewer.getText();
        if (!aux.equals("0")) {
            this.jtxtViewer.setText(aux + "0");
        }
    }//GEN-LAST:event_jbtnZeroActionPerformed

    private void jbtnOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnOneActionPerformed
        // TODO add your handling code here:
        String aux = this.jtxtViewer.getText();
        if (aux.equals("0")) {
            this.jtxtViewer.setText("1");
        } else {
            this.jtxtViewer.setText(aux + "1");
        }
    }//GEN-LAST:event_jbtnOneActionPerformed

    private void jbtnTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTwoActionPerformed
        // TODO add your handling code here:
        String aux = this.jtxtViewer.getText();
        if (aux.equals("0")) {
            this.jtxtViewer.setText("2");
        } else {
            this.jtxtViewer.setText(aux + "2");
        }
    }//GEN-LAST:event_jbtnTwoActionPerformed

    private void jbtnThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnThreeActionPerformed
        // TODO add your handling code here:
        String aux = this.jtxtViewer.getText();
        if (aux.equals("0")) {
            this.jtxtViewer.setText("3");
        } else {
            this.jtxtViewer.setText(aux + "3");
        }
    }//GEN-LAST:event_jbtnThreeActionPerformed

    private void jbtnFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnFourActionPerformed
        // TODO add your handling code here:
        String aux = this.jtxtViewer.getText();
        if (aux.equals("0")) {
            this.jtxtViewer.setText("4");
        } else {
            this.jtxtViewer.setText(aux + "4");
        }
    }//GEN-LAST:event_jbtnFourActionPerformed

    private void jbtnFiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnFiveActionPerformed
        // TODO add your handling code here:
        String aux = this.jtxtViewer.getText();
        if (aux.equals("0")) {
            this.jtxtViewer.setText("5");
        } else {
            this.jtxtViewer.setText(aux + "5");
        }
    }//GEN-LAST:event_jbtnFiveActionPerformed

    private void jbtnSixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSixActionPerformed
        // TODO add your handling code here:
        String aux = this.jtxtViewer.getText();
        if (aux.equals("0")) {
            this.jtxtViewer.setText("6");
        } else {
            this.jtxtViewer.setText(aux + "6");
        }
    }//GEN-LAST:event_jbtnSixActionPerformed

    private void jbtnSevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSevenActionPerformed
        // TODO add your handling code here:
        String aux = this.jtxtViewer.getText();
        if (aux.equals("0")) {
            this.jtxtViewer.setText("7");
        } else {
            this.jtxtViewer.setText(aux + "7");
        }
    }//GEN-LAST:event_jbtnSevenActionPerformed

    private void jbtnEightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEightActionPerformed
        // TODO add your handling code here:
        String aux = this.jtxtViewer.getText();
        if (aux.equals("0")) {
            this.jtxtViewer.setText("8");
        } else {
            this.jtxtViewer.setText(aux + "8");
        }
    }//GEN-LAST:event_jbtnEightActionPerformed

    private void jbtnNineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNineActionPerformed
        // TODO add your handling code here:
        String aux = this.jtxtViewer.getText();
        if (aux.equals("0")) {
            this.jtxtViewer.setText("9");
        } else {
            this.jtxtViewer.setText(aux + "9");
        }
    }//GEN-LAST:event_jbtnNineActionPerformed

    private void jbtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddActionPerformed
        // TODO add your handling code here:
        double value = Double.parseDouble(this.jtxtViewer.getText());
        this.jtxtViewer.setText("0");
        calculo.setFirst(value);
        calculo.setOperation("+");
    }//GEN-LAST:event_jbtnAddActionPerformed

    private void jbtnSubtractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSubtractActionPerformed
        // TODO add your handling code here:
        double value = Double.parseDouble(this.jtxtViewer.getText());
        this.jtxtViewer.setText("0");
        calculo.setFirst(value);
        calculo.setOperation("-");
    }//GEN-LAST:event_jbtnSubtractActionPerformed

    private void jbtnMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMultiplyActionPerformed
        // TODO add your handling code here:
        double value = Double.parseDouble(this.jtxtViewer.getText());
        this.jtxtViewer.setText("0");
        calculo.setFirst(value);
        calculo.setOperation("*");
    }//GEN-LAST:event_jbtnMultiplyActionPerformed

    private void jbtnDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDivideActionPerformed
        // TODO add your handling code here:
        double value = Double.parseDouble(this.jtxtViewer.getText());
        this.jtxtViewer.setText("0");
        calculo.setFirst(value);
        calculo.setOperation("/");
    }//GEN-LAST:event_jbtnDivideActionPerformed

    private void jbtnEqualsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEqualsActionPerformed
        // TODO add your handling code here:
        double value = Double.parseDouble(this.jtxtViewer.getText());
        calculo.setSecond(value);
        this.jtxtViewer.setText(String.valueOf(calculo.calcular()));
    }//GEN-LAST:event_jbtnEqualsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCalculadora().setVisible(true);
            }
        });
    }
    
    private static Calculo calculo = new Calculo();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnAdd;
    private javax.swing.JButton jbtnClear;
    private javax.swing.JButton jbtnComma;
    private javax.swing.JButton jbtnDivide;
    private javax.swing.JButton jbtnEight;
    private javax.swing.JButton jbtnEquals;
    private javax.swing.JButton jbtnFive;
    private javax.swing.JButton jbtnFour;
    private javax.swing.JButton jbtnMultiply;
    private javax.swing.JButton jbtnNine;
    private javax.swing.JButton jbtnOne;
    private javax.swing.JButton jbtnSeven;
    private javax.swing.JButton jbtnSix;
    private javax.swing.JButton jbtnSubtract;
    private javax.swing.JButton jbtnThree;
    private javax.swing.JButton jbtnTwo;
    private javax.swing.JButton jbtnZero;
    private javax.swing.JPanel jpanelBase;
    private javax.swing.JPanel jpanelBotoes;
    private javax.swing.JPanel jpanelVisor;
    private javax.swing.JTextField jtxtViewer;
    // End of variables declaration//GEN-END:variables
}
