/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import javax.swing.JCheckBox;
import javax.swing.event.EventListenerList;

/**
 *
 * @author gabriel
 */
public class CheckBoxAndTextArea extends javax.swing.JFrame {

    private String text;

    /**
     * Creates new form Screen3
     */
    public CheckBoxAndTextArea() {
        initComponents();
        text = "";
    }

    void checkAndChange(JCheckBox element, String elementName) {
        if (element.isSelected()) {
            text += elementName+" está selecionado!\n";
        } else {
            text = text.replace(elementName+" está selecionado!\n", "");
        }
        SelectedElements.setText(text);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Element1 = new javax.swing.JCheckBox();
        Element2 = new javax.swing.JCheckBox();
        Element3 = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        SelectedElements = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Element1.setText("Elemento 1");
        Element1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Element1ActionPerformed(evt);
            }
        });

        Element2.setText("Elemento 2");
        Element2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Element2ActionPerformed(evt);
            }
        });

        Element3.setText("Elemento 3");
        Element3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Element3ActionPerformed(evt);
            }
        });

        SelectedElements.setColumns(20);
        SelectedElements.setRows(5);
        jScrollPane1.setViewportView(SelectedElements);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Element1)
                    .addComponent(Element2)
                    .addComponent(Element3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(165, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(Element1)
                .addGap(18, 18, 18)
                .addComponent(Element2)
                .addGap(18, 18, 18)
                .addComponent(Element3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Element1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Element1ActionPerformed
        // TODO add your handling code here:
        checkAndChange(Element1, "Elemento 1");

    }//GEN-LAST:event_Element1ActionPerformed

    private void Element2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Element2ActionPerformed
        // TODO add your handling code here:
        checkAndChange(Element2, "Elemento 2");
    }//GEN-LAST:event_Element2ActionPerformed

    private void Element3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Element3ActionPerformed
        // TODO add your handling code here:
        checkAndChange(Element3, "Elemento 3");
    }//GEN-LAST:event_Element3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckBoxAndTextArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckBoxAndTextArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckBoxAndTextArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckBoxAndTextArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckBoxAndTextArea().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Element1;
    private javax.swing.JCheckBox Element2;
    private javax.swing.JCheckBox Element3;
    private javax.swing.JTextArea SelectedElements;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
